### PR TITLE
Allow overridable configs if config key already exists

### PR DESCRIPTION
**Pull request by nocive**

### CODE REVIEW

**Comment by misantron** [comment]
@nocive thanks for your PR

**Comment by nocive** [comment]
@misantron you're very welcome, actually opened the PR by mistake on the upstream repo, but then thought "why not?" :)

Thanks for the speedy reaction to it, one less fork for me to use :trophy: :+1:

**Comment by misantron** [comment]
@nocive I'll try to make a stable version in a few days.
May be the better way is to throw an exception when container key is already exists?
Something like:

```php
if (isset($app[$this->key])) {
    throw new \RuntimeException('Key is already exists');
}

$app[$this->key] = new Container();
```

**Comment by nocive** [comment]
@misantron no, the point with my PR is to be able to use cascade configurations, ie, our use case is the following:

- we have a mix of json and yaml configurations (the json ones are legacy)
- we load the json config first
- we load the yaml config second (both use the same ```config``` key)
- we want the yaml config to be merged with the json config and override any keys that exist

I totally understand this might not be something you wish to have in your implementation though, so feel free to revert it if you don't want this behaviour to be allowed :)

**Pull request merged**
